/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CustomSortPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// types.ts
var DEFAULT_SETTINGS = {
  orders: {}
};

// sorter.ts
var import_obsidian = require("obsidian");
function sortItems(items, order) {
  if (order.length === 0)
    return items;
  const orderMap = /* @__PURE__ */ new Map();
  for (let i = 0; i < order.length; i++) {
    orderMap.set(order[i], i);
  }
  const inOrder = [];
  const unknownFolders = [];
  const unknownFiles = [];
  for (const item of items) {
    if (!item || !item.file)
      continue;
    const name = item.file.name;
    const pos = orderMap.get(name);
    if (pos !== void 0) {
      inOrder.push({ item, pos });
    } else if (item.file instanceof import_obsidian.TFolder) {
      unknownFolders.push(item);
    } else if (item.file instanceof import_obsidian.TFile) {
      unknownFiles.push(item);
    }
  }
  inOrder.sort((a, b) => a.pos - b.pos);
  unknownFolders.sort(
    (a, b) => a.file.name.localeCompare(b.file.name, void 0, { sensitivity: "base", numeric: true })
  );
  unknownFiles.sort(
    (a, b) => a.file.name.localeCompare(b.file.name, void 0, { sensitivity: "base", numeric: true })
  );
  return [
    ...inOrder.map((x) => x.item),
    ...unknownFolders,
    ...unknownFiles
  ];
}

// drag-handler.ts
var import_obsidian2 = require("obsidian");
var FOLDER_AUTO_EXPAND_DELAY_MS = 2e3;
var DragHandler = class {
  constructor(plugin) {
    this.state = {
      draggedEl: null,
      draggedFile: null,
      placeholder: null,
      folderDropTarget: null
    };
    this.cleanupFns = [];
    this.folderExpandTimer = null;
    /** Map of parentPath -> set of visible child names (from rendered explorer rows). */
    this.visibleByParent = /* @__PURE__ */ new Map();
    /** Map of parentPath -> visible child names in their rendered DOM order. */
    this.visibleOrderByParent = /* @__PURE__ */ new Map();
    this.plugin = plugin;
  }
  /**
   * Set up drag-and-drop on all items in the File explorer.
   */
  setup(explorerView) {
    var _a, _b, _c;
    this.cleanup();
    const fileItems = explorerView.fileItems;
    if (!fileItems)
      return;
    const explorerEl = (_a = explorerView.containerEl) == null ? void 0 : _a.querySelector(
      ".nav-files-container"
    );
    if (explorerEl) {
      const onExplorerDragOver = (e) => {
        if (!this.state.draggedFile)
          return;
        const rowTarget = this.resolveRowTarget(e);
        if (rowTarget) {
          this.handleDragOver(e, rowTarget.el, rowTarget.file);
          return;
        }
        const target = this.resolveGapTarget(e);
        if (!target)
          return;
        if (this.isSameFile(this.state.draggedFile, target.file) || !this.canDropOnTarget(this.state.draggedFile, target.file)) {
          this.suppressInvalidDrag(e);
          return;
        }
        e.preventDefault();
        e.stopImmediatePropagation();
        if (e.dataTransfer)
          e.dataTransfer.dropEffect = "move";
        this.showPlaceholder(target.el, target.insertBefore);
      };
      const onExplorerDragEnter = (e) => {
        if (!this.state.draggedFile)
          return;
        const rowTarget = this.resolveRowTarget(e);
        if (rowTarget) {
          this.handleDragOver(e, rowTarget.el, rowTarget.file);
          return;
        }
        const target = this.resolveGapTarget(e);
        if (!target)
          return;
        if (this.isSameFile(this.state.draggedFile, target.file) || !this.canDropOnTarget(this.state.draggedFile, target.file)) {
          this.suppressInvalidDrag(e);
          return;
        }
        e.preventDefault();
        e.stopImmediatePropagation();
        if (e.dataTransfer)
          e.dataTransfer.dropEffect = "move";
        this.showPlaceholder(target.el, target.insertBefore);
      };
      const onExplorerDrop = (e) => {
        void (async () => {
          if (!this.state.draggedFile)
            return;
          const rowTarget = this.resolveRowTarget(e);
          if (rowTarget) {
            const rect = rowTarget.el.getBoundingClientRect();
            await this.handleDrop(
              e,
              rowTarget.el,
              rowTarget.file,
              e.clientY < rect.top + rect.height / 2
            );
            return;
          }
          const target = this.resolveGapTarget(e);
          if (!target)
            return;
          if (this.isSameFile(this.state.draggedFile, target.file) || !this.canDropOnTarget(this.state.draggedFile, target.file)) {
            this.suppressInvalidDrag(e);
            return;
          }
          e.preventDefault();
          e.stopImmediatePropagation();
          await this.handleDrop(e, target.el, target.file, target.insertBefore);
        })();
      };
      explorerEl.addEventListener("dragenter", onExplorerDragEnter, true);
      explorerEl.addEventListener("dragover", onExplorerDragOver, true);
      explorerEl.addEventListener("drop", onExplorerDrop, true);
      this.cleanupFns.push(() => {
        explorerEl.removeEventListener("dragenter", onExplorerDragEnter, true);
        explorerEl.removeEventListener("dragover", onExplorerDragOver, true);
        explorerEl.removeEventListener("drop", onExplorerDrop, true);
      });
    }
    this.captureVisibleOrder(fileItems);
    const childrenByParent = /* @__PURE__ */ new Map();
    for (const item of Object.values(fileItems)) {
      if (!item || !item.file || !item.selfEl)
        continue;
      if (item.file.path === "")
        continue;
      const parentPath = (_c = (_b = item.file.parent) == null ? void 0 : _b.path) != null ? _c : "";
      if (!childrenByParent.has(parentPath)) {
        childrenByParent.set(parentPath, []);
      }
      childrenByParent.get(parentPath).push({
        item,
        el: item.selfEl
      });
    }
    for (const [, children] of childrenByParent) {
      for (const { item, el } of children) {
        this.setupItemDrag(el, item, fileItems);
      }
    }
  }
  captureVisibleOrder(fileItems) {
    var _a, _b;
    this.visibleByParent.clear();
    this.visibleOrderByParent.clear();
    const visibleChildrenByParent = /* @__PURE__ */ new Map();
    for (const item of Object.values(fileItems)) {
      if (!item || !item.file || !item.selfEl)
        continue;
      if (item.file.path === "")
        continue;
      const itemEl = item.selfEl;
      if (itemEl.offsetParent === null)
        continue;
      const parentPath = (_b = (_a = item.file.parent) == null ? void 0 : _a.path) != null ? _b : "";
      if (!this.visibleByParent.has(parentPath)) {
        this.visibleByParent.set(parentPath, /* @__PURE__ */ new Set());
      }
      this.visibleByParent.get(parentPath).add(item.file.name);
      if (!visibleChildrenByParent.has(parentPath)) {
        visibleChildrenByParent.set(parentPath, []);
      }
      visibleChildrenByParent.get(parentPath).push({
        name: item.file.name,
        el: itemEl
      });
    }
    for (const [parentPath, children] of visibleChildrenByParent) {
      children.sort((a, b) => {
        if (a.el === b.el)
          return 0;
        return a.el.compareDocumentPosition(b.el) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1;
      });
      this.visibleOrderByParent.set(
        parentPath,
        children.map((child) => child.name)
      );
    }
  }
  setupItemDrag(el, item, fileItems) {
    el.addClass("drag-drop-sort-draggable");
    const file = item.file;
    const onDragStart = (e) => {
      this.captureVisibleOrder(fileItems);
      this.state.draggedEl = el;
      this.state.draggedFile = file;
      this.removePlaceholder();
      this.clearFolderDropTarget();
      el.addClass("drag-drop-sort-dragging");
      if (e.dataTransfer) {
        e.dataTransfer.effectAllowed = "move";
        e.dataTransfer.setData("text/plain", file.path);
      }
    };
    const onDragEnd = () => {
      el.removeClass("drag-drop-sort-dragging");
      this.removePlaceholder();
      this.clearFolderDropTarget();
      this.state.draggedEl = null;
      this.state.draggedFile = null;
    };
    const onDragOver = (e) => {
      this.handleDragOver(e, el, file);
    };
    const onDrop = (e) => {
      void (async () => {
        if (!this.state.draggedFile)
          return;
        if (this.isSameFile(this.state.draggedFile, file))
          return;
        const rect = el.getBoundingClientRect();
        const insertBefore = e.clientY < rect.top + rect.height / 2;
        await this.handleDrop(e, el, file, insertBefore);
      })();
    };
    el.addEventListener("dragstart", onDragStart);
    el.addEventListener("dragend", onDragEnd);
    el.addEventListener("dragover", onDragOver, true);
    el.addEventListener("drop", onDrop, true);
    this.cleanupFns.push(() => {
      el.removeEventListener("dragstart", onDragStart);
      el.removeEventListener("dragend", onDragEnd);
      el.removeEventListener("dragover", onDragOver, true);
      el.removeEventListener("drop", onDrop, true);
      el.removeClass("drag-drop-sort-draggable");
    });
  }
  resolveRowTarget(e) {
    var _a;
    const target = ((_a = e.targetNode) == null ? void 0 : _a.instanceOf(Element)) ? e.targetNode : null;
    const el = (target == null ? void 0 : target.instanceOf(HTMLElement)) ? target.closest(".tree-item-self") : null;
    if (!(el == null ? void 0 : el.instanceOf(HTMLElement)))
      return null;
    const row = el.closest(".tree-item");
    if (!(row == null ? void 0 : row.instanceOf(HTMLElement)))
      return null;
    const file = this.getFileForRow(row);
    return file ? { el, file } : null;
  }
  resolveGapTarget(e) {
    var _a;
    const placeholder = this.state.placeholder;
    if (placeholder == null ? void 0 : placeholder.parentElement) {
      const next = placeholder.nextElementSibling;
      const previous = placeholder.previousElementSibling;
      const row2 = (next == null ? void 0 : next.instanceOf(HTMLElement)) && next.classList.contains("tree-item") ? next : (previous == null ? void 0 : previous.instanceOf(HTMLElement)) && previous.classList.contains("tree-item") ? previous : null;
      if (row2) {
        const file2 = this.getFileForRow(row2);
        if (file2) {
          return {
            row: row2,
            el: row2.querySelector(".tree-item-self"),
            file: file2,
            insertBefore: row2 === next
          };
        }
      }
    }
    const target = ((_a = e.targetNode) == null ? void 0 : _a.instanceOf(Element)) ? e.targetNode : null;
    const children = target == null ? void 0 : target.closest(".tree-item-children");
    if (!children)
      return null;
    const rows = Array.from(children.children).filter(
      (child) => child.instanceOf(HTMLElement) && child.classList.contains("tree-item")
    );
    for (const row2 of rows) {
      const self = row2.querySelector(".tree-item-self");
      if (!(self == null ? void 0 : self.instanceOf(HTMLElement)))
        continue;
      const rect = self.getBoundingClientRect();
      if (e.clientY < rect.top + rect.height / 2) {
        const file2 = this.getFileForRow(row2);
        const el2 = row2.querySelector(".tree-item-self");
        return file2 && (el2 == null ? void 0 : el2.instanceOf(HTMLElement)) ? { row: row2, el: el2, file: file2, insertBefore: true } : null;
      }
    }
    const row = rows.at(-1);
    if (!row)
      return null;
    const file = this.getFileForRow(row);
    const el = row.querySelector(".tree-item-self");
    return file && (el == null ? void 0 : el.instanceOf(HTMLElement)) ? { row, el, file, insertBefore: false } : null;
  }
  getFileForRow(row) {
    var _a;
    const path = (_a = row.querySelector(".tree-item-self")) == null ? void 0 : _a.getAttribute("data-path");
    const file = path ? this.plugin.app.vault.getAbstractFileByPath(path) : null;
    return file != null ? file : null;
  }
  handleDragOver(e, el, file) {
    var _a;
    if (!this.state.draggedFile)
      return;
    e.preventDefault();
    e.stopImmediatePropagation();
    if (e.dataTransfer)
      e.dataTransfer.dropEffect = "move";
    if (this.isSameFile(this.state.draggedFile, file) || !this.canDropOnTarget(this.state.draggedFile, file)) {
      this.removePlaceholder();
      this.clearFolderDropTarget();
      if (e.dataTransfer)
        e.dataTransfer.dropEffect = "none";
      return;
    }
    if (file instanceof import_obsidian2.TFolder && this.isFolderEmptyOrCollapsed(el, file)) {
      this.removePlaceholder();
      this.setFolderDropTarget(el, file);
      return;
    }
    if (file instanceof import_obsidian2.TFolder && ((_a = this.state.folderDropTarget) == null ? void 0 : _a.el) === el && this.state.folderDropTarget.autoExpanded) {
      this.removePlaceholder();
      return;
    }
    const firstChildTarget = this.getFirstChildTarget(el, file, e.clientY);
    if (firstChildTarget) {
      this.clearFolderDropTarget();
      this.showPlaceholder(firstChildTarget.el, true);
      return;
    }
    if (!this.canDropOnTarget(this.state.draggedFile, file))
      return;
    this.clearFolderDropTarget();
    const rect = el.getBoundingClientRect();
    this.showPlaceholder(el, e.clientY < rect.top + rect.height / 2);
  }
  suppressInvalidDrag(e) {
    e.preventDefault();
    e.stopImmediatePropagation();
    this.removePlaceholder();
    this.clearFolderDropTarget();
    if (e.dataTransfer)
      e.dataTransfer.dropEffect = "none";
  }
  showPlaceholder(row, insertBefore) {
    var _a;
    this.clearFolderDropTarget();
    const existing = this.state.placeholder;
    const alreadyInPosition = (existing == null ? void 0 : existing.parentElement) === row.parentElement && (insertBefore ? (existing == null ? void 0 : existing.nextElementSibling) === row : (existing == null ? void 0 : existing.previousElementSibling) === row);
    if (alreadyInPosition)
      return;
    this.removePlaceholder();
    this.state.placeholder = createDiv({
      cls: "drag-drop-sort-drop-indicator"
    });
    (_a = row.parentElement) == null ? void 0 : _a.insertBefore(
      this.state.placeholder,
      insertBefore ? row : row.nextSibling
    );
  }
  async handleDrop(e, el, file, insertBefore) {
    var _a, _b, _c, _d;
    e.preventDefault();
    e.stopImmediatePropagation();
    this.removePlaceholder();
    const draggedFile = this.state.draggedFile;
    if (!draggedFile)
      return;
    const draggedName = draggedFile.name;
    const sourceParent = (_b = (_a = draggedFile.parent) == null ? void 0 : _a.path) != null ? _b : "";
    if (this.isSameFile(draggedFile, file) || !this.canDropOnTarget(draggedFile, file)) {
      this.clearFolderDropTarget();
      if (e.dataTransfer)
        e.dataTransfer.dropEffect = "none";
      return;
    }
    if (this.state.folderDropTarget !== null) {
      const targetFolder = this.state.folderDropTarget.folder;
      if (!this.canDropOnTarget(draggedFile, file))
        return;
      if (!this.canMoveToParent(draggedFile, targetFolder.path))
        return;
      if (sourceParent !== targetFolder.path) {
        const destinationPath = targetFolder.path ? `${targetFolder.path}/${draggedName}` : draggedName;
        const oldDraggedPath = draggedFile.path;
        this.plugin.beginInternalMove();
        try {
          await this.plugin.app.fileManager.renameFile(
            draggedFile,
            destinationPath
          );
        } catch (e2) {
          return;
        } finally {
          this.plugin.endInternalMove();
        }
        if (draggedFile instanceof import_obsidian2.TFolder) {
          this.remapFolderOrderKeys(oldDraggedPath, draggedFile.path);
        }
      }
      this.applyMoveIntoFolder(sourceParent, targetFolder.path, draggedName);
      this.clearFolderDropTarget();
      await this.plugin.saveSettings();
      this.cleanupStaleOrders();
      return;
    }
    const firstChildTarget = this.getFirstChildTarget(el, file, e.clientY);
    if (firstChildTarget) {
      await this.handleDrop(e, firstChildTarget.el, firstChildTarget.file, true);
      return;
    }
    this.clearFolderDropTarget();
    const destinationParent = (_d = (_c = file.parent) == null ? void 0 : _c.path) != null ? _d : "";
    if (sourceParent !== destinationParent) {
      if (!this.canMoveToParent(draggedFile, destinationParent))
        return;
      const oldDraggedPath = draggedFile.path;
      const destinationPath = destinationParent ? `${destinationParent}/${draggedName}` : draggedName;
      this.plugin.beginInternalMove();
      try {
        await this.plugin.app.fileManager.renameFile(
          draggedFile,
          destinationPath
        );
      } catch (e2) {
        return;
      } finally {
        this.plugin.endInternalMove();
      }
      if (draggedFile instanceof import_obsidian2.TFolder) {
        this.remapFolderOrderKeys(oldDraggedPath, draggedFile.path);
      }
    }
    this.applyReorder(
      sourceParent,
      destinationParent,
      draggedName,
      file.name,
      insertBefore
    );
    await this.plugin.saveSettings();
    this.cleanupStaleOrders();
  }
  canDropOnTarget(dragged, target) {
    var _a, _b;
    const destinationParent = (_b = (_a = target.parent) == null ? void 0 : _a.path) != null ? _b : "";
    if (dragged.path === destinationParent)
      return false;
    if (destinationParent.startsWith(dragged.path + "/"))
      return false;
    return true;
  }
  isSameFile(first, second) {
    return first !== null && second !== null && first.path === second.path;
  }
  // ── Folder-header drop target ────────────────────────────
  isFolderCollapsed(el) {
    const row = el.closest(".tree-item");
    return (row == null ? void 0 : row.classList.contains("is-collapsed")) === true || row !== null && !row.querySelector(":scope > .tree-item-children");
  }
  isFolderEmptyOrCollapsed(el, folder) {
    if (this.isFolderCollapsed(el))
      return true;
    for (const child of folder.children) {
      if (this.isVisible(folder.path, child.name))
        return false;
    }
    return true;
  }
  setFolderDropTarget(el, folder) {
    var _a;
    if (((_a = this.state.folderDropTarget) == null ? void 0 : _a.el) === el)
      return;
    this.clearFolderDropTarget();
    el.addClass("drag-drop-sort-drop-folder");
    this.state.folderDropTarget = { el, folder, autoExpanded: false };
    this.scheduleFolderExpansion(el, folder);
  }
  scheduleFolderExpansion(el, folder) {
    if (folder.children.length === 0 || !this.isFolderCollapsed(el))
      return;
    this.folderExpandTimer = window.setTimeout(() => {
      this.folderExpandTimer = null;
      const target = this.state.folderDropTarget;
      if (!this.state.draggedFile || !target || target.el !== el || target.folder !== folder || !this.isFolderCollapsed(el)) {
        return;
      }
      const collapseIcon = el.querySelector(
        ":scope > .collapse-icon"
      );
      if (!collapseIcon) {
        console.warn(
          "Drag and Drop Sort: unable to auto-expand folder without a collapse control.",
          folder.path
        );
        return;
      }
      collapseIcon.click();
      target.autoExpanded = true;
      window.setTimeout(() => this.refreshVisibleOrder(), 0);
    }, FOLDER_AUTO_EXPAND_DELAY_MS);
  }
  clearFolderDropTarget() {
    if (this.folderExpandTimer !== null) {
      window.clearTimeout(this.folderExpandTimer);
      this.folderExpandTimer = null;
    }
    if (this.state.folderDropTarget) {
      this.state.folderDropTarget.el.removeClass("drag-drop-sort-drop-folder");
      this.state.folderDropTarget = null;
    }
  }
  getFirstChildTarget(el, file, clientY) {
    if (!(file instanceof import_obsidian2.TFolder) || this.isFolderEmptyOrCollapsed(el, file)) {
      return null;
    }
    const rect = el.getBoundingClientRect();
    if (clientY < rect.top + rect.height / 2)
      return null;
    const row = el.closest(".tree-item");
    const childRows = row == null ? void 0 : row.querySelector(":scope > .tree-item-children");
    if (!childRows)
      return null;
    for (const child of Array.from(childRows.children)) {
      if (!child.instanceOf(HTMLElement) || !child.classList.contains("tree-item") || !child.offsetParent) {
        continue;
      }
      const childEl = child.querySelector(":scope > .tree-item-self");
      const childFile = this.getFileForRow(child);
      if ((childEl == null ? void 0 : childEl.instanceOf(HTMLElement)) && childFile) {
        return { el: childEl, file: childFile };
      }
    }
    return null;
  }
  refreshVisibleOrder() {
    const leaf = this.plugin.getFileExplorerLeaf();
    if (!leaf)
      return;
    const view = leaf.view;
    if (view.fileItems) {
      this.captureVisibleOrder(view.fileItems);
    }
  }
  applyMoveIntoFolder(sourceParent, targetFolderPath, draggedName) {
    if (sourceParent === targetFolderPath)
      return;
    const sourceWorking = this.getWorkingOrder(sourceParent).filter(
      (name) => name !== draggedName
    );
    if (sourceWorking.length > 0) {
      this.plugin.settings.orders[sourceParent] = this.mergeHiddenBack(
        sourceParent,
        sourceWorking
      );
    } else {
      delete this.plugin.settings.orders[sourceParent];
    }
  }
  canMoveToParent(dragged, destinationParent) {
    if (dragged.path === destinationParent)
      return false;
    if (destinationParent.startsWith(dragged.path + "/"))
      return false;
    return true;
  }
  applyReorder(sourceParent, destinationParent, draggedName, targetName, insertBefore) {
    if (sourceParent !== destinationParent) {
      const sourceWorking = this.getWorkingOrder(sourceParent).filter(
        (name) => name !== draggedName
      );
      if (sourceWorking.length > 0) {
        this.plugin.settings.orders[sourceParent] = this.mergeHiddenBack(
          sourceParent,
          sourceWorking
        );
      } else {
        delete this.plugin.settings.orders[sourceParent];
      }
    }
    const destinationWorking = this.getWorkingOrder(destinationParent).filter(
      (name) => name !== draggedName
    );
    const targetIdx = destinationWorking.indexOf(targetName);
    if (targetIdx === -1) {
      destinationWorking.push(draggedName);
    } else if (insertBefore) {
      destinationWorking.splice(targetIdx, 0, draggedName);
    } else {
      destinationWorking.splice(targetIdx + 1, 0, draggedName);
    }
    this.plugin.settings.orders[destinationParent] = this.mergeHiddenBack(
      destinationParent,
      destinationWorking
    );
  }
  getWorkingOrder(parentPath) {
    var _a;
    const order = (_a = this.plugin.settings.orders[parentPath]) != null ? _a : [];
    const visibleChildren = this.getVisibleChildren(parentPath);
    const working = order.filter(
      (name) => this.isVisible(parentPath, name) && visibleChildren.includes(name)
    );
    for (const child of visibleChildren) {
      if (!working.includes(child)) {
        working.push(child);
      }
    }
    return working;
  }
  getVisibleChildren(parentPath) {
    const folder = this.plugin.app.vault.getFolderByPath(parentPath);
    if (!folder)
      return [];
    const renderedOrder = this.visibleOrderByParent.get(parentPath);
    if (renderedOrder)
      return renderedOrder;
    return folder.children.map((c) => c.name).filter((name) => this.isVisible(parentPath, name));
  }
  isVisible(parentPath, name) {
    var _a, _b;
    return (_b = (_a = this.visibleByParent.get(parentPath)) == null ? void 0 : _a.has(name)) != null ? _b : true;
  }
  remapFolderOrderKeys(oldPath, newPath) {
    const remapped = {};
    for (const [key, value] of Object.entries(this.plugin.settings.orders)) {
      if (key === oldPath || key.startsWith(oldPath + "/")) {
        const suffix = key.slice(oldPath.length);
        remapped[newPath + suffix] = value;
      } else {
        remapped[key] = value;
      }
    }
    this.plugin.settings.orders = remapped;
  }
  /**
   * After reordering visible items, merge hidden items back at their
   * original relative positions so they don't get lost.
   */
  mergeHiddenBack(parentPath, visibleOrder) {
    const folder = this.plugin.app.vault.getFolderByPath(parentPath);
    if (!folder)
      return visibleOrder;
    const result = [...visibleOrder];
    const visibleSet = new Set(visibleOrder);
    let insertOffset = 0;
    for (const child of folder.children) {
      if (!visibleSet.has(child.name)) {
        const idx = Math.min(result.length, insertOffset++);
        result.splice(idx, 0, child.name);
      } else {
        insertOffset = result.indexOf(child.name) + 1;
      }
    }
    return result;
  }
  /** Remove order entries for deleted/moved items. */
  cleanupStaleOrders() {
    for (const [path, order] of Object.entries(this.plugin.settings.orders)) {
      const folder = this.plugin.app.vault.getFolderByPath(path);
      if (!folder) {
        delete this.plugin.settings.orders[path];
        continue;
      }
      const names = new Set(folder.children.map((c) => c.name));
      const cleaned = order.filter((n) => names.has(n));
      if (cleaned.length !== order.length) {
        if (cleaned.length === 0) {
          delete this.plugin.settings.orders[path];
        } else {
          this.plugin.settings.orders[path] = cleaned;
        }
      }
    }
  }
  removePlaceholder() {
    if (this.state.placeholder) {
      this.state.placeholder.remove();
      this.state.placeholder = null;
    }
    for (const indicator of Array.from(
      document.querySelectorAll(".drag-drop-sort-drop-indicator")
    )) {
      indicator.remove();
    }
  }
  cleanup() {
    this.removePlaceholder();
    this.clearFolderDropTarget();
    this.state.draggedEl = null;
    this.state.draggedFile = null;
    for (const fn of this.cleanupFns) {
      fn();
    }
    this.cleanupFns = [];
    this.visibleByParent.clear();
    this.visibleOrderByParent.clear();
  }
};

// main.ts
var MOVE_ACTIONS = [
  { action: "up", title: "Move up", icon: "arrow-up" },
  { action: "down", title: "Move down", icon: "arrow-down" },
  { action: "top", title: "Move to top", icon: "arrow-up-to-line" },
  { action: "bottom", title: "Move to bottom", icon: "arrow-down-to-line" }
];
function patchPrototype(obj, methodName, factory) {
  const proto = obj.constructor.prototype;
  const original = proto[methodName];
  if (typeof original !== "function")
    return () => void 0;
  proto[methodName] = factory(original);
  return () => {
    proto[methodName] = original;
  };
}
var CustomSortPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.uninstallPatch = null;
    this.dragSetupTimer = null;
    this.patched = false;
    this.internalMoveDepth = 0;
  }
  async onload() {
    await this.loadSettings();
    this.dragHandler = new DragHandler(this);
    this.app.workspace.onLayoutReady(() => {
      this.patchFileExplorer();
    });
    this.registerEvent(
      this.app.vault.on("create", () => this.requestSort())
    );
    this.registerEvent(
      this.app.vault.on("delete", () => this.requestSort())
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (this.internalMoveDepth > 0) {
          this.requestSort();
          return;
        }
        void this.handleRename(file, oldPath);
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        if (!this.patched) {
          this.patchFileExplorer();
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file, source) => {
        if (source !== "file-explorer-context-menu")
          return;
        this.addFileMenuItems(menu, file);
      })
    );
    this.registerSortCommands();
  }
  onunload() {
    var _a, _b;
    if (this.uninstallPatch) {
      this.uninstallPatch();
      this.uninstallPatch = null;
    }
    if (this.dragSetupTimer !== null) {
      window.clearTimeout(this.dragSetupTimer);
    }
    this.dragHandler.cleanup();
    this.patched = false;
    const leaf = this.getFileExplorerLeaf();
    if (leaf) {
      (_b = (_a = leaf.view).requestSort) == null ? void 0 : _b.call(_a);
    }
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.requestSort();
  }
  /** Get the File explorer leaf (public for DragHandler). */
  getFileExplorerLeaf() {
    const leaves = this.app.workspace.getLeavesOfType("file-explorer");
    return leaves.length > 0 ? leaves[0] : null;
  }
  /** Request a re-sort of the File explorer and re-setup drag handlers. */
  requestSort() {
    var _a, _b;
    const leaf = this.getFileExplorerLeaf();
    if (leaf) {
      (_b = (_a = leaf.view).requestSort) == null ? void 0 : _b.call(_a);
    }
    this.scheduleDragSetup();
  }
  // ─── Patching ────────────────────────────────────────────
  patchFileExplorer() {
    var _a;
    const leaf = this.getFileExplorerLeaf();
    if (!leaf)
      return;
    const view = leaf.view;
    if (!view || typeof view.getSortedFolderItems !== "function") {
      return;
    }
    if (this.patched)
      return;
    const getPlugin = () => this;
    this.uninstallPatch = patchPrototype(
      view,
      "getSortedFolderItems",
      (original) => function(folder) {
        const items = original.call(this, folder);
        const plugin = getPlugin();
        const order = plugin.settings.orders[folder.path];
        if (!order || order.length === 0)
          return items;
        return plugin.sortExplorerItems(items, order);
      }
    );
    this.patched = true;
    this.register(() => {
      if (this.uninstallPatch) {
        this.uninstallPatch();
        this.uninstallPatch = null;
        this.patched = false;
      }
    });
    (_a = view.requestSort) == null ? void 0 : _a.call(view);
    this.scheduleDragSetup();
  }
  scheduleDragSetup() {
    if (this.dragSetupTimer !== null) {
      window.clearTimeout(this.dragSetupTimer);
    }
    this.dragSetupTimer = window.setTimeout(() => {
      this.dragSetupTimer = null;
      const leaf = this.getFileExplorerLeaf();
      if (leaf) {
        this.dragHandler.setup(leaf.view);
      }
    }, 100);
  }
  /** Sort items using custom order — interspersed files & folders. */
  sortExplorerItems(items, order) {
    return sortItems(items, order);
  }
  registerSortCommands() {
    for (const moveAction of MOVE_ACTIONS) {
      this.addCommand({
        id: `move-${moveAction.action}`,
        name: moveAction.title,
        checkCallback: (checking) => this.runMoveCommand(moveAction.action, checking)
      });
    }
    this.addCommand({
      id: "reset-sort",
      name: "Reset sort",
      checkCallback: (checking) => this.runResetCommand(false, checking)
    });
    this.addCommand({
      id: "reset-sort-all-descendants",
      name: "Reset sort (all descendants)",
      checkCallback: (checking) => this.runResetCommand(true, checking)
    });
  }
  runMoveCommand(action, checking) {
    const file = this.getActiveExplorerFile();
    const parent = file == null ? void 0 : file.parent;
    if (!file || !parent)
      return false;
    const availableActions = this.getAvailableMoveActions(file, parent);
    if (!availableActions.some((moveAction) => moveAction.action === action)) {
      return false;
    }
    if (!checking) {
      void this.moveFile(file, action);
    }
    return true;
  }
  runResetCommand(includeChildren, checking) {
    const file = this.getActiveExplorerFile();
    if (!(file instanceof import_obsidian3.TFolder))
      return false;
    if (!checking) {
      void this.resetFolderSort(file, includeChildren);
    }
    return true;
  }
  getActiveExplorerFile() {
    var _a, _b, _c, _d, _e, _f;
    const view = (_a = this.getFileExplorerLeaf()) == null ? void 0 : _a.view;
    if (!view)
      return null;
    return (_f = (_e = (_c = (_b = view.tree) == null ? void 0 : _b.focusedItem) == null ? void 0 : _c.file) != null ? _e : (_d = view.activeDom) == null ? void 0 : _d.file) != null ? _f : null;
  }
  addFileMenuItems(menu, file) {
    const parent = file.parent;
    const folder = file instanceof import_obsidian3.TFolder ? file : null;
    const moveActions = parent ? this.getAvailableMoveActions(file, parent) : [];
    if (folder === null && moveActions.length === 0)
      return;
    menu.addSeparator();
    if (import_obsidian3.Platform.isDesktop && !import_obsidian3.Platform.isTablet) {
      menu.addItem((item) => {
        const submenu = item.setSubmenu();
        item.setTitle("Drag and Drop Sort commands").setIcon("move");
        this.addSortMenuItems(submenu, file, folder, moveActions);
      });
    } else {
      this.addSortMenuItems(menu, file, folder, moveActions);
    }
  }
  addSortMenuItems(menu, file, folder, moveActions) {
    if (folder !== null) {
      menu.addItem(
        (item) => item.setTitle("Reset sort").setIcon("rotate-ccw").onClick(() => void this.resetFolderSort(folder))
      );
      menu.addItem(
        (item) => item.setTitle("Reset sort (all descendants)").setIcon("folder-tree").onClick(() => void this.resetFolderSort(folder, true))
      );
      if (moveActions.length > 0) {
        menu.addSeparator();
      }
    }
    for (const moveAction of moveActions) {
      menu.addItem(
        (item) => item.setTitle(moveAction.title).setIcon(moveAction.icon).onClick(() => void this.moveFile(file, moveAction.action))
      );
    }
  }
  getAvailableMoveActions(file, parent) {
    const order = this.getCurrentOrder(parent);
    const index = order.indexOf(file.name);
    if (index === -1 || order.length < 2)
      return [];
    return MOVE_ACTIONS.filter(({ action }) => {
      switch (action) {
        case "up":
        case "top":
          return index > 0;
        case "down":
        case "bottom":
          return index < order.length - 1;
      }
    });
  }
  getCurrentOrder(parent) {
    var _a;
    const children = parent.children.slice();
    const childNames = new Set(children.map((child) => child.name));
    const savedOrder = (_a = this.settings.orders[parent.path]) != null ? _a : [];
    const seen = /* @__PURE__ */ new Set();
    const orderedNames = savedOrder.filter((name) => {
      if (!childNames.has(name) || seen.has(name))
        return false;
      seen.add(name);
      return true;
    });
    const unknownFolders = children.filter((child) => !seen.has(child.name) && child instanceof import_obsidian3.TFolder).sort((a, b) => this.compareFileNames(a, b));
    const unknownFiles = children.filter((child) => !seen.has(child.name) && !(child instanceof import_obsidian3.TFolder)).sort((a, b) => this.compareFileNames(a, b));
    return [
      ...orderedNames,
      ...unknownFolders.map((child) => child.name),
      ...unknownFiles.map((child) => child.name)
    ];
  }
  compareFileNames(left, right) {
    return left.name.localeCompare(right.name, void 0, {
      sensitivity: "base",
      numeric: true
    });
  }
  async resetFolderSort(folder, includeChildren = false) {
    const prefix = `${folder.path}/`;
    const pathsToReset = Object.keys(this.settings.orders).filter(
      (path) => path === folder.path || includeChildren && path.startsWith(prefix)
    );
    if (pathsToReset.length === 0)
      return;
    for (const path of pathsToReset) {
      delete this.settings.orders[path];
    }
    await this.saveSettings();
  }
  async moveFile(file, action) {
    const parent = file.parent;
    if (!parent)
      return;
    const order = this.getCurrentOrder(parent);
    const currentIndex = order.indexOf(file.name);
    if (currentIndex === -1 || order.length < 2)
      return;
    let targetIndex = currentIndex;
    switch (action) {
      case "up":
        targetIndex -= 1;
        break;
      case "down":
        targetIndex += 1;
        break;
      case "top":
        targetIndex = 0;
        break;
      case "bottom":
        targetIndex = order.length - 1;
        break;
    }
    if (targetIndex === currentIndex)
      return;
    order.splice(currentIndex, 1);
    order.splice(targetIndex, 0, file.name);
    this.settings.orders[parent.path] = order;
    await this.saveSettings();
  }
  /** Mark beginning of plugin-controlled move operation. */
  beginInternalMove() {
    this.internalMoveDepth += 1;
  }
  /** Mark end of plugin-controlled move operation. */
  endInternalMove() {
    this.internalMoveDepth = Math.max(0, this.internalMoveDepth - 1);
  }
  /**
   * Keep custom order stable when Obsidian renames/moves items.
   *
   * - Rename in same parent: replace old item name with new item name at same index.
   * - Move to different parent: remove from old parent order and append to new parent order (if present).
   * - Folder rename/move: also remap order keys for the folder path and its descendants.
   */
  async handleRename(file, oldPath) {
    const newPath = file.path;
    const oldParent = this.getParentPath(oldPath);
    const newParent = this.getParentPath(newPath);
    const oldName = this.getBaseName(oldPath);
    const newName = file.name;
    let changed = false;
    const oldOrder = this.settings.orders[oldParent];
    if (oldOrder && oldOrder.length > 0) {
      const idx = oldOrder.indexOf(oldName);
      if (idx !== -1) {
        if (oldParent === newParent) {
          oldOrder[idx] = newName;
        } else {
          oldOrder.splice(idx, 1);
          if (oldOrder.length === 0) {
            delete this.settings.orders[oldParent];
          }
        }
        changed = true;
      }
    }
    if (oldParent !== newParent) {
      const newOrder = this.settings.orders[newParent];
      if (newOrder && !newOrder.includes(newName)) {
        newOrder.push(newName);
        changed = true;
      }
    }
    if (file instanceof import_obsidian3.TFolder) {
      const remappedOrders = {};
      let remapped = false;
      for (const [key, value] of Object.entries(this.settings.orders)) {
        if (key === oldPath || key.startsWith(oldPath + "/")) {
          const suffix = key.slice(oldPath.length);
          remappedOrders[newPath + suffix] = value;
          remapped = true;
        } else {
          remappedOrders[key] = value;
        }
      }
      if (remapped) {
        this.settings.orders = remappedOrders;
        changed = true;
      }
    }
    if (changed) {
      await this.saveSettings();
    } else {
      this.requestSort();
    }
  }
  getParentPath(path) {
    const idx = path.lastIndexOf("/");
    return idx === -1 ? "" : path.substring(0, idx);
  }
  getBaseName(path) {
    const idx = path.lastIndexOf("/");
    return idx === -1 ? path : path.substring(idx + 1);
  }
};

/* nosourcemap */